config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  get 'homes', to: 'homes#index'
  
  root to: 'homes#index'
  resources :mylists, only: [:index, :create, :edit, :show, :update, :destroy]
  resources :users, only: :show
  resources :rooms, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :grouplists, only: [:index, :create, :edit, :show, :update, :destroy] do
     resources :comments, only: [:create, :edit, :update, :destroy]
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/models/mylist.rb
class Mylist < ApplicationRecord
  belongs_to :user
  has_many_attached :main_images #追加

  with_options presence: true do
    validates :title, length: { maximum: 40 }
    validates :start_time
  end
  validates :text, length: { maximum: 200 }
  validate :images_length
  

  private
  def images_length
    if main_images.length > 6
      errors.add(:main_images)
    end
  end
end

app/controllers/mylists_controller.rb
class MylistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mylist, only: [:edit, :show, :ensure_correct_customer]
  before_action :move_to_index, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_customer, only: [:edit, :update, :destroy]

  def index
    @mylist = Mylist.new
    @user = current_user
    @mylists = Mylist.where(user_id: current_user).order(start_time: 'asc')
  end

  def edit
  end

  def create
    @mylist = Mylist.new(mylists_params)
    @user = current_user
    @mylists = Mylist.where(user_id: current_user)
    if @mylist.user_id == current_user.id && @mylist.save
      flash[:notice] = '♫予定を登録しました♫'
      redirect_to mylists_path
    else
      flash.now[:alert] = 'タイトルor画像枚数に不備があります'
      render :index
    end
  end

  def update
    if @mylist.update(mylists_params)
      flash[:notice] = '♫予定を更新しました♫'
      redirect_to mylists_path(params[:id])
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @mylist.destroy
    flash[:notice] = '予定を削除しました'
    redirect_to mylists_path
  end

  private

  def set_mylist
    @mylist = Mylist.find(params[:id])
  end

  def ensure_correct_customer
    redirect_to mylists_path unless @mylist.user_id == current_user.id
  end

  def mylists_params
    params.require(:mylist).permit(:title, :start_time, :text, :user, main_images: []).merge(user_id: current_user.id)
  end

  def move_to_index
    @mylist = Mylist.find(params[:id])
    redirect_to action: :index unless current_user.id == @mylist.user_id
  end
end

app/helpers/mylists_helper.rb
module MylistsHelper
end

app/views/mylists/edit.html.erb
<div class="wrapper">
  <%= render "shared/third-header" %>
  <div class="page-title-show"><i class="fa-solid fa-paw"></i>ToDo編集<i class="fa-solid fa-paw"></i></div>

  <div class="main-contents-show">
    <div class="article-show" id="article-list">
      <%= form_with model: @mylist, local: true do |f| %>
      <%# エラーメッセージ%>
      <%= render 'shared/error_messages', model: f.object %>
        <div class="article-post-date-edit">
          <label for="title"><i class="fa-solid fa-pen-to-square"></i>タイトル(必須)</label><br>
          <%= f.text_field :title, class:"title-content-edit", placeholder:"（40文字まで)", maxlength:"40"%>
        </div>
        <div class="article-title-edit">
          <label for="start_time"><i class="fa-solid fa-calendar-days"></i>日付(必須)</label><br>
          <%= f.datetime_select :start_time, {use_month_numbers: true, start_year: Date.today.year, datetime_separator: '<h4 class="fb-txt font-weight-bold my-2"><i class="fa-solid fa-clock-rotate-left"></i>時間</h4>'},{class: "date-content", id: 'ymd-date'}%>
        </div>
        <div class="article-text-edit">
          <label for="text"><i class="fa-solid fa-feather-pointed"></i>詳細</label><br>
          <%= f.text_area :text, class:"text-content", placeholder:"（200文字まで)", maxlength:"200"%>
        </div>
        <div class="article-image-edit">
          <label for="image"><i class="fa-solid fa-camera-retro"></i>画像</label>
          <p class="file-field"><%= f.file_field :main_images, class: "image-edit", multiple: true%></p>
        </div>
        <div class="register-field-edit">
          <%= f.submit class: "register-btn-edit" %>
         </div>
      <% end %>
    </div>
  </div>
  <div class="btn_registration" id="btn_registration">
    <%= link_to "マイページに戻る",  mylists_path, class: 'btn_registration' %>
  </div>
  
</div> 
<%= render "shared/second-footer" %>

app/views/mylists/index.html.erb
<div class="wrapper">
  <%= render "shared/third-header" %>
  
  <div class="top-title">
    <div class="rooms-index">
      <%= link_to 'ルームに移動する', rooms_path, {class: "btn-shadow"} %>
    </div>
    <div class="page-title"><i class="fa-solid fa-paw"></i><%= "#{current_user.nickname}のToDo"%><i class="fa-solid fa-paw"></i></div>
  </div>
  <%# 新規投稿部分 %>
  <div class="flex-contents">
    <div class="side-var" id="hidden-nav">
      <%= form_with model: @mylist, local: true do |f| %>
      <%# メッセージ%>
      <div class="flash-index"><%= flash[:notice] %></div>
      <%# エラーメッセージ%>
      <div class="flash-index-error"><%= flash.now[:alert] %></div>
      <div class="field row">
        <P class="schedule-input-title"><i class="fa-solid fa-paw"></i>予定を登録する<i class="fa-solid fa-paw"></i></P>
        <label for="title"><i class="fa-solid fa-pen-to-square"></i>タイトル(必須)</label>
        <p><%= f.text_field :title, class:"title-content", placeholder:"（40文字まで)", maxlength:"40"%></p>
        <label for="start_time"><i class="fa-solid fa-calendar-days"></i>日付(必須)</label>
        <p><%= f.datetime_select :start_time, {use_month_numbers: true, start_year: Date.today.year, datetime_separator: '<h4 class="fb-txt font-weight-bold my-2"><i class="fa-solid fa-clock-rotate-left"></i>時間</h4>'},{class: "date-content", id: 'ymd-date'}%></p>
        <label for="text"><i class="fa-solid fa-feather-pointed"></i>詳細</label>
        <p><%= f.text_area :text, class:"text-content-todo", placeholder:"（200文字まで)", maxlength:"200"%></p>
        <label for="image"><i class="fa-solid fa-camera-retro"></i>画像(6枚まで)</label>
        <p class="file-field"><%= f.file_field :main_images, class: "image", multiple: true%></p>
      </div>
      <div class="register-field">
       <%= f.submit class: "register-btn" %>
      </div>
      <% end %>
    </div>
   <%# カレンダー部分%>
    <div class="calendar">
      <%= month_calendar events: @user.mylists do |date, mylists| %>
        <%= date.day %>
        <% mylists.each do |mylist| %>
		      <div class="calendar-schedule">
		        <%= link_to mylist.title, mylist_path(mylist.id) %>
		      </div>
		    <% end %>
      <% end %>
    </div>
  </div>
  <%# リスト表示部分 %>
  <div class="main-contents">
    <div class="articles">
      <% @mylists.each do |mylist| %>
        <div class="article" id="article-list">
          <div class="article-overview">
            <%= link_to mylist_path(mylist.id) do %>
              <p class="article-post-date"><i class="fa-solid fa-paw"></i>
                <%= mylist.start_time.strftime("%Y年%m月%d日 %H:%M")%>
              </p>
              <p class="article-title">
                <%= mylist.title%>
              </p>
            <% end %>
            <div class="article-information">
              <div class="article-check">
                  <div class="article-edit-button" id="edit" data=<%= @mylist.id %>>
                    <%= link_to "編集", edit_mylist_path(mylist.id)%>
                  </div>
                  <div class="article-check-button" id="hidden-btn" data=<%= @mylist.id %>>
                    <%= link_to "完了", mylist_path(mylist.id), method: :delete, data: { confirm: 'タスク完了(削除)しますか？'}%>
                  </div>
              </div>
            </div>
          </div>
          <div class="many-images">
          <% if mylist.main_images.present? %>
            <% mylist.main_images.each do |image| %>
              <%= link_to image, "data-lightbox" => image do %>
                <%= image_tag image, class: "article-image-show", height: '250', :style=>"width:300;"%>
              <% end %>
            <% end %>  
          <% else %>
            <div class="no-image">noimege</div>
          <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div> 
<div class="plus-btn" id="plus-nav">
<%= link_to image_tag("btn.png", class:"btn-smartphone"), '#' %>
</div>
<%= render "shared/second-footer" %> 

app/views/mylists/show.html.erb
<div class="wrapper">
  <%= render "shared/third-header" %>
  <div class="page-title-show"><i class="fa-solid fa-paw"></i>ToDo詳細<i class="fa-solid fa-paw"></i></div>
  
  <div class="main-contents-show">
    <div class="article-show" id="article-list">
      <p class="article-post-date-show">
        <span class="show-title"><i class="fa-solid fa-clock-rotate-left"></i>日時</span><br><%= @mylist.start_time.strftime("%Y年%m月%d日 %H:%M")%>
      </p>
      <p class="article-title-show">
        <span class="show-title"><i class="fa-solid fa-pen-to-square"></i>タイトル</span><br><%= @mylist.title%>
      </p>
      <% if @mylist.text.present? %>
        <p class="article-text-show">
         <span class="show-title"><i class="fa-solid fa-feather-pointed"></i>内容</span><br><%= @mylist.text%>
        </p>
      <% else %>
        <p class="article-text-show">
          <span class="show-title"><i class="fa-solid fa-feather-pointed"></i>内容</span><br><%= "(投稿なし)"%>
        </p>
      <% end %>
           
      <div class="article-information-show">
        <div class="article-check-show">
          <% if @mylist.main_images.present? %>
            <div class="image-title"><i class="fa-solid fa-camera-retro"></i></div>
            <% @mylist.main_images.each do |image| %>
              <%= link_to image, "data-lightbox" => image do %>
                <%= image_tag image, class: "article-image-show", height: '250', :style=>"width:300;"%>
              <% end %>
            <% end %>  
          <% else %>
            <div class="image-title"><i class="fa-solid fa-camera-retro"></i></div>
            <div class="no-image-show">noimege</div>
          <% end %>
            <div class="flex-btn">
              <div class="article-edit-button-show" id="edit" data=<%= @mylist.id %>>
                <%= link_to "編集", edit_mylist_path(@mylist.id)%>
              </div>
              <div class="article-check-button-show" id="hidden-btn" data=<%= @mylist.id %>>
                <%= link_to "完了", mylist_path(@mylist.id), method: :delete, data: { confirm: 'タスク完了(削除)しますか？'}%>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  <div class="btn_registration" id="btn_registration">
    <%= link_to "マイページに戻る",  mylists_path, class: 'btn_registration' %>
  </div>
</div> 
<%= render "shared/second-footer" %>