config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  get 'homes', to: 'homes#index'
  
  root to: 'homes#index'
  resources :mylists, only: [:index, :create, :edit, :show, :update, :destroy]
  resources :users, only: :show
  resources :rooms, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :grouplists, only: [:index, :create, :edit, :show, :update, :destroy] do
     resources :comments, only: [:create, :edit, :update, :destroy]
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/models/grouplist.rb
class Grouplist < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :room
  has_many_attached :main_images #追加

  with_options presence: true do
    validates :title, length: { maximum: 40 }
    validates :start_time
  end
  validates :text, length: { maximum: 200 }
  validate :images_length

  private
  def images_length
    if main_images.length > 6
      errors.add(:main_images)
    end
  end
end

app/controllers/grouplists_controller.rb
class GrouplistsController < ApplicationController
  before_action :logged_in_room
  before_action :authenticate_user!
  before_action :set_room
  before_action :set_grouplist, only: [:edit, :show, :update, :destroy]

  def index
    @grouplist = Grouplist.new
    @grouplists = Grouplist.where(room_id: @room.id).order(start_time: 'asc')
  end

  def edit
  end

  def create
    @grouplist = Grouplist.new(grouplists_params)
    @grouplists = Grouplist.where(room_id: @room.id)
    if @grouplist.room_id == @room.id && @grouplist.save
      flash[:notice] = '♫予定を登録しました♫'
      redirect_to room_grouplists_path(@room.id)
    else
      flash.now[:alert] = "タイトルor画像枚数に不備があります"
      render :index
    end
  end

  def show
    @comment = Comment.new
    @comments = Comment.where(grouplist_id: @grouplist.id, room_id: @grouplist.room_id).order(updated_at: 'desc')
  end

  def update
    if @grouplist.update(grouplists_params)
      flash[:notice] = '♫予定を更新しました♫'
      redirect_to room_grouplists_path(@room.id)
    else
      render :edit
    end
  end

  def destroy
    @grouplist.destroy
    flash[:notice] = '予定を削除しました'
    redirect_to room_grouplists_path(@room.id)
  end

  private
  

  def grouplists_params
    params.require(:grouplist).permit(:title, :start_time, :text, :user, :room, main_images: []).merge(user_id: current_user.id,
                                                                                              room_id: @room.id)
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_grouplist
    @grouplist = Grouplist.find(params[:id])
  end

  def logged_in_room
    @room = Room.find(params[:room_id])
    redirect_to login_path unless logged_in? && current_room.id == @room.id
  end
end

app/helpers/grouplists_helper.rb
module GrouplistsHelper
end

app/views/grouplists/edit.html.erb
<div class="wrapper">
  <%= render "shared/fifth-header" %>
  <div class="page-title-show"><i class="fa-solid fa-paw"></i>ToDo編集<i class="fa-solid fa-paw"></i></div>

  <div class="main-contents-show">
    <div class="article-show" id="article-list">
      <%= form_with model: [@room, @grouplist], local: true do |f| %>
      <%# エラーメッセージ%>
      <%= render 'shared/error_messages', model: f.object %>
        <div class="article-post-date-edit">
          <label for="title"><i class="fa-solid fa-pen-to-square"></i>タイトル(必須)</label><br>
          <%= f.text_field :title, class:"title-content-edit", placeholder:"（40文字まで)", maxlength:"40"%>
        </div>
        <div class="article-title-edit">
          <label for="start_time"><i class="fa-solid fa-calendar-days"></i>日付(必須)</label><br>
          <%= f.datetime_select :start_time, {use_month_numbers: true, start_year: Date.today.year, datetime_separator: '<h4 class="fb-txt font-weight-bold my-2"><i class="fa-solid fa-clock-rotate-left"></i>時間</h4>'},{class: "date-content", id: 'ymd-date'}%>
        </div>
        <div class="article-text-edit">
          <label for="text"><i class="fa-solid fa-feather-pointed"></i>詳細</label><br>
          <%= f.text_area :text, class:"text-content", placeholder:"（200文字まで)", maxlength:"200"%>
        </div>
        <div class="article-image-edit">
          <label for="image"><i class="fa-solid fa-camera-retro"></i>画像</label>
          <p class="file-field"><%= f.file_field :main_images, class: "image-edit", multiple: true%></p>
        </div>
        <div class="register-field-edit">
          <%= f.submit class: "register-btn-edit" %>
         </div>
      <% end %>
    </div>
  </div>
  
  <% if user_signed_in? %>
    <div class="btn_registration" id="btn_registration">
      <%= link_to "ルームページに戻る",  room_grouplists_path(@room.id), class: 'btn_registration' %>
    </div>
  <% end %>
</div> 
<%= render "shared/fourth-footer" %>

app/views/grouplists/index.html.erb
<div class="wrapper">
<% if logged_in? %>
  <%= render "shared/fifth-header" %>
  

  <div class="top-title">
    <div class="rooms-index">
      <%= link_to 'ルームを退室する', rooms_path, {class: "btn-shadow"}%>
    </div>
    <div class="page-title"><i class="fa-solid fa-paw"></i><%= "#{@room.name}" %><i class="fa-solid fa-paw"></i></div>
  </div>

  <%# 新規投稿部分 %>
  <div class="flex-contents">
    <div class="side-var">
      <%= form_with model:[@room, @grouplist], local: true do |f| %>
      <%# メッセージ%>
      <div class="flash-index"><%= flash[:notice] %></div>
      <%# エラーメッセージ%>
      <div class="flash-index-error"><%= flash.now[:alert] %></div>
      <div class="field row">
        <P class="schedule-input-title"><i class="fa-solid fa-paw"></i>予定を登録する<i class="fa-solid fa-paw"></i></P>
        <label for="title"><i class="fa-solid fa-pen-to-square"></i>タイトル(必須)</label>
        <p><%= f.text_field :title, class:"title-content", placeholder:"（40文字まで)", maxlength:"40"%></p>
        <label for="start_time"><i class="fa-solid fa-calendar-days"></i>日付(必須)</label>
        <p><%= f.datetime_select :start_time, {use_month_numbers: true, start_year: Date.today.year, datetime_separator: '<h4 class="fb-txt font-weight-bold my-2"><i class="fa-solid fa-clock-rotate-left"></i>時間</h4>'},{class: "date-content", id: 'ymd-date'}%></p>
        <label for="text"><i class="fa-solid fa-feather-pointed"></i>詳細</label>
        <p><%= f.text_area :text, class:"text-content", placeholder:"（200文字まで)", maxlength:"200"%></p>
        <label for="image"><i class="fa-solid fa-camera-retro"></i>画像(6枚まで)</label>
        <p class="file-field"><%= f.file_field :main_images, class: "image", multiple: true%></p>
      </div>
      <div class="register-field">
       <%= f.submit class: "register-btn" %>
      </div>
      <% end %>
    </div>
  
   <%# カレンダー部分%>
    <div class="calendar">
      <%= month_calendar events: @grouplists do |date, grouplists| %>
        <%= date.day %>
        <% grouplists.each do |grouplist| %>
		      <div class="calendar-schedule">
		        <%= link_to grouplist.title, room_grouplist_path(grouplist.room_id, grouplist.id) %>
		      </div>
		    <% end %>
      <% end %>
    </div>
  </div>

  <%# リスト表示部分 %>
  <div class="main-contents">
    <div class="articles">
      <% @grouplists.each do |grouplist| %>
        <div class="article" id="article-list">
          <div class="article-overview">
            <%= link_to room_grouplist_path(grouplist.room_id, grouplist.id) do %>
              <p class="article-post-date"><i class="fa-solid fa-paw"></i>
                <%= grouplist.start_time.strftime("%Y年%m月%d日 %H:%M")%>
              </p>
              <p class="article-title">
                <%= grouplist.title%>
              </p>
           <% end %>
            <div class="article-information">
              <div class="article-check-room-index">
                  <div class="article-edit-button-room" id="edit" data=<%= grouplist.id %>>
                    <%= link_to "編集", edit_room_grouplist_path(grouplist.room_id, grouplist.id)%>
                  </div>
                  <div class="article-check-button-room" id="hidden-btn" data=<%= grouplist.id %>>
                    <%= link_to "完了", room_grouplist_path(grouplist.room_id, grouplist.id), method: :delete, data: { confirm: 'タスク完了(削除)しますか？'}%>
                  </div>
                  <div class="article-check-button-contributor" id="hidden-btn" data=<%= grouplist.id %>>
                    <%= link_to "#{grouplist.user.nickname}さん",  user_path(grouplist.user_id)%>
                  </div>
              </div>
            </div>
          </div>
          <div class="many-images">
          <% if grouplist.main_images.present? %>
            <% grouplist.main_images.each do |image| %>
              <%= link_to image, "data-lightbox" => image do %>
                <%= image_tag image, class: "article-image-show", height: '250', :style=>"width:300;"%>
              <% end %>
            <% end %>  
          <% else %>
          <div class="no-image">noimege</div>
          <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div> 
<div class="plus-btn">
  <%= link_to image_tag("btn.png", class:"btn-smartphone"), '#' %>
  </div>
<%= render "shared/fourth-footer" %> 
<% else %>
<%= render "shared/third-header" %>
<p>タスクの管理ができるアプリです。まずはログインをしてください。</p>
<%= link_to "ログイン", login_path%>
<%= render "shared/second-footer" %> 
<% end %>

app/views/grouplists/show.html.erb
<div class="wrapper">
  <%= render "shared/fifth-header" %>
  <div class="page-title-show"><i class="fa-solid fa-paw"></i>ToDo詳細<i class="fa-solid fa-paw"></i></div>
  <%# メッセージ%>
  <div class="flash-index"><%= flash[:notice] %></div>
  <div class="main-contents-comment">
      <div class="article-show" id="article-list">
          <p class="article-post-date-show">
            <span class="show-title"><i class="fa-solid fa-clock-rotate-left"></i>日時</span><br><%= @grouplist.start_time.strftime("%Y年%m月%d日 %H:%M")%>
          </p>
          <p class="article-title-show">
            <span class="show-title"><i class="fa-solid fa-pen-to-square"></i>タイトル</span><br><%= @grouplist.title%>
          </p>
          <% if @grouplist.text.present? %>
          <p class="article-text-show">
            <span class="show-title"><i class="fa-solid fa-feather-pointed"></i>内容</span><br><%= @grouplist.text%>
          </p>
          <% else %>
          <p class="article-text-show">
            <span class="show-title"><i class="fa-solid fa-feather-pointed"></i>内容</span><br><%= "(投稿なし)"%>
          </p>
          <% end %>
          <p class="article-text-show">
            <span class="show-title"><i class="fa-solid fa-person-circle-check"></i>投稿者</span><br><%= link_to "#{@grouplist.user.nickname}さん",  user_path(@grouplist.user_id)%>
          </p>
           
          <div class="article-information-show">
            <div class="article-check-show">
              <% if @grouplist.main_images.present? %>
              <div class="image-title"><i class="fa-solid fa-camera-retro"></i></div>
              <% @grouplist.main_images.each do |image| %>
                <%= link_to image, "data-lightbox" => image do %>
                  <%= image_tag image, class: "article-image-show", height: '250', :style=>"width:300;"%>
                <% end %>
              <% end %>  
              <% else %>
              <div class="image-title"><i class="fa-solid fa-camera-retro"></i></div>
              <div class="no-image-show">noimege</div>
              <% end %>
              <div class="flex-btn">
                <div class="article-edit-button-show" id="edit" data=<%= @grouplist.id %>>
                  <%= link_to "編集", edit_room_grouplist_path(@room.id, @grouplist.id)%>
                </div>
                <div class="article-check-button-show" id="hidden-btn" data=<%= @grouplist.id %>>
                <%= link_to "完了", room_grouplist_path(@room.id, @grouplist.id), method: :delete, data: { confirm: 'タスク完了(削除)しますか？'}%>
                </div>
              </div>
            </div>
          </div>
      </div>
  </div>
  <div class="comment-title"><i class="fa-solid fa-paw"></i><%= "「#{@grouplist.title}」へのコメント"%><i class="fa-solid fa-paw"></i></div>
  <div class="flash-index"><%= flash.now[:alert] %></div>
  <div class="comments-field">
    <div class="room-list-comment">
      <div class="room-list-supplement">(更新日時順)</div>
      <% if @comments.present? %>
        <% @comments.each do |comment| %>
          <div class="room-comment">
            <div class="room-text">
              <%= comment.text%>
            </div>
            <div class="room-nickname-comment">
              <% if current_user.id == comment.user.id %>
                <%= link_to "編集(#{current_user.nickname})", edit_room_grouplist_comment_path(@room.id, @grouplist.id, comment.id)%>
              <% else %>
                <%= "投：#{comment.user.nickname}" %>
              <% end %>
            </div>
            <div class="room-date-comment">
              <%= l comment.created_at %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="not-comment-text">現在コメントはありません</p>
      <% end %>
    </div>
  </div>
  <div class="btn_registration" id="btn_registration">
    <%= link_to "ルームページに戻る",  room_grouplists_path(@room.id), class: 'btn_registration' %>
  </div>
</div> 
<div class="comment-room-wrapper">
<%= form_with model: [@room, @grouplist, @comment], local: true do |f| %>
  <div class="comment-flex">
    <div class="article-post-comment">
      <label for="text">コメント</label><br>
      <%= f.text_area :text, class:"title-content-comment", placeholder:"（200文字まで)", maxlength:"200"%>
    </div>
    <div class="register-field-comment">
      <%= f.submit class: "register-btn-comment", value: "POST" %>
    </div>
  </div>  
<% end %>
</div> 