config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  get 'homes', to: 'homes#index'
  
  root to: 'homes#index'
  resources :mylists, only: [:index, :create, :edit, :show, :update, :destroy]
  resources :users, only: :show
  resources :rooms, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :grouplists, only: [:index, :create, :edit, :show, :update, :destroy] do
     resources :comments, only: [:create, :edit, :update, :destroy]
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_fifth-header.html.erb
<header class='top_page_header_nav'>
  <div class='left_menu_nav'>
    <div class="nav-logo">
      <%= link_to image_tag("logo.png", class:"logo-icon"), room_grouplists_path(@room.id) %>
    </div>
   <!-- ナビゲーション -->
    <div class="right-nav">
      <nav class="headerNav">
        <ul class="navList">
          <li class="navItem">
            <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class:"link-nav" %>
          </li>
          <li class="navItem">
            <%= link_to 'マイページに戻る', mylists_path, class:"link-nav" %>
          </li>
          <li class="navItem">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"link-nav"%>
          </li>
        </ul>
      </nav>
    </div>
  </div>
<!-- ハンバーガーボタン -->
  <div class="hamburger_btn" id="js-hamburger">
    <span class="hamburger_line hamburger_line_1"></span>
    <span class="hamburger_line hamburger_line_2"></span>
    <span class="hamburger_line hamburger_line_3"></span>
  </div>
<!-- ハンバーガーメニュをクリックした後に現れる半透明の背景-->
    <div class="black-bg" id="js-black-bg"></div>
  
</header>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='image-details'>
  <%= link_to image_tag("logo.png", class:"logo-icon"), "/" %>
  </div>
  <nav class='footer-contents'>
   <p>© Copyright 2022 First ToDo All rights reserved.</p>
  </nav>
</div>

app/views/shared/_fourth-footer.html.erb
<div class='footer'>
  <div class='image-details'>
  <%= link_to image_tag("logo.png", class:"logo-icon"), room_grouplists_path(@room.id) %>
  </div>
  <nav class='footer-contents'>
   <p>© Copyright 2022 First ToDo All rights reserved.</p>
  </nav>
</div>

app/views/shared/_fourth-header.html.erb
<header class='top_page_header_nav'>
  <div class='left_menu_nav'>
    <div class="nav-logo">
      <%= link_to image_tag("logo.png", class:"logo-icon"), rooms_path %>
    </div>
   <!-- ナビゲーション -->
    <div class="right-nav">
      <nav class="headerNav">
        <ul class="navList">
          <li class="navItem">
            <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class:"link-nav"%>
          </li>
          <li class="navItem">
            <%= link_to 'マイページに戻る', mylists_path, class:"link-nav"%>
          </li>
          <li class="navItem">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"link-nav"%>
          </li>
        </ul>
      </nav>
    </div>
  </div>
<!-- ハンバーガーボタン -->
  <div class="hamburger_btn" id="js-hamburger">
    <span class="hamburger_line hamburger_line_1"></span>
    <span class="hamburger_line hamburger_line_2"></span>
    <span class="hamburger_line hamburger_line_3"></span>
  </div>
<!-- ハンバーガーメニュをクリックした後に現れる半透明の背景-->
    <div class="black-bg" id="js-black-bg"></div>
  
</header>

app/views/shared/_header.html.erb
<header class='top_page_header'>
  <div class='left_menu'>
  <%= link_to image_tag("logo.png", class:"logo-icon"), root_path %>
  </div>
  <div class='right_menu'>
    <ul class="right_menu-smartphone">
    <% if user_signed_in? %>
      <li><%= link_to "#{current_user.nickname}さん", user_path(current_user.id) %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<div class='footer'>
  <div class='image-details'>
  <%= link_to image_tag("logo.png", class:"logo-icon"), mylists_path %>
  </div>
  <nav class='footer-contents'>
   <p>© Copyright 2022 First ToDo All rights reserved.</p>
  </nav>
</div>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"),  root_path %>
</header>

app/views/shared/_third-footer.html.erb
<div class='footer'>
  <div class='image-details'>
  <%= link_to image_tag("logo.png", class:"logo-icon"), rooms_path %>
  </div>
  <nav class='footer-contents'>
   <p>© Copyright 2022 First ToDo All rights reserved.</p>
  </nav>
</div>

app/views/shared/_third-header.html.erb
<header class='top_page_header'>
  <div class='left_menu'>
  <%= link_to image_tag("logo.png", class:"logo-icon"), mylists_path %>
  </div>
  <div class='right_menu'>
    <ul class='right_menu-smartphone'>
      <li><%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: "logout" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
    </ul>
  </div>
</header>