config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  get 'homes', to: 'homes#index'
  
  root to: 'homes#index'
  resources :mylists, only: [:index, :create, :edit, :show, :update, :destroy]
  resources :users, only: :show
  resources :rooms, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :grouplists, only: [:index, :create, :edit, :show, :update, :destroy] do
     resources :comments, only: [:create, :edit, :update, :destroy]
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/models/room.rb
class Room < ApplicationRecord
  has_secure_password
  belongs_to :user
  has_many :grouplists, dependent: :destroy

  with_options presence: true do
    validates :name, length: { maximum: 40 }
  end

  # 検索機能
  def self.search(search)
    if search != ''
      Room.where('name LIKE(?)', "%#{search}%")
    else
      Room.all
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rooms, only: [:index, :create]
  before_action :set_room, only: [:edit, :update]

  def index
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.user_id == current_user.id && @room.save
      redirect_to rooms_path
    else
      render :index
    end
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to rooms_path
    else
      render :edit
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
  end

  # 検索機能
  def search
    @rooms = Room.search(params[:keyword]).order(created_at: 'desc')
    @room = Room.new
  end

  private

  def set_rooms
    @rooms = Room.all.order(created_at: 'desc')
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :password, :password_confirmation, :user).merge(user_id: current_user.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="wrapper">
  <%= render "shared/fourth-header" %>
  <div class="page-title-show"><i class="fa-solid fa-paw"></i>Room編集<i class="fa-solid fa-paw"></i></div>

  <%= form_with model: @room, local: true do |f| %>
    <div class="new-room-wrapper">
      <%# エラーメッセージ%>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="article-post-room-index">
        <label for="name"><i class="fa-solid fa-house-circle-exclamation"></i>ルーム名(必須)</label><br>
        <%= f.text_field :name, class:"title-content-room-index", placeholder:"（40文字まで)", maxlength:"40"%>
      </div>
      <div class="article-post-room-index">
        <label for="password"><i class="fa-solid fa-key"></i>ルームキー(必須)</label><br>
        <%= f.password_field :password, class:"title-content-room-index", placeholder:"（ルームキーを設定してください)"%>
      </div>
      <div class="article-post-room-index">
        <label for="password_confirmation">ルームキー(確認)</label><br>
        <%= f.password_field :password_confirmation, class:"title-content-room-index", placeholder:"（同じキーを入力してください)"%>
      </div>
      <div class="register-field-room-index">
        <%= f.submit class: "register-btn-room-index", value: "更新する" %>
      </div>
      <div class="btn-position">
      <div class="room-destroy-button" id="hidden-btn" data=<%= @room.id %>>
        <%= link_to "ルーム削除", room_path(@room.id), method: :delete, data: { confirm: 'ルームが削除されますがよろしいですか？'}%>
      </div>
      </div>
    </div>   
  <% end %>
  <div class="btn_registration" id="btn_registration">
    <%= link_to "ルームに戻る",  rooms_path, class: 'btn_registration' %>
  </div>
</div> 
<%= render "shared/third-footer" %>

app/views/rooms/index.html.erb
<div class="wrapper">
  <%= render "shared/fourth-header" %>
  <div class="page-title-show"><i class="fa-solid fa-paw"></i>Roomページ<i class="fa-solid fa-paw"></i></div>

  <%= form_with model: @room, local: true do |f| %>
    <div class="new-room-wrapper">
      <%# エラーメッセージ%>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="article-post-room-index">
        <label for="name"><i class="fa-solid fa-house-circle-exclamation"></i>ルーム名(必須)</label><br>
        <%= f.text_field :name, class:"title-content-room-index", placeholder:"（40文字まで)", maxlength:"40"%>
      </div>
      <div class="article-post-room-index">
        <label for="password"><i class="fa-solid fa-key"></i>ルームキー(必須)</label><br>
        <%= f.password_field :password, class:"title-content-room-index", placeholder:"（ルームキーを設定してください)"%>
      </div>
      <div class="article-post-room-index">
        <label for="password_confirmation">ルームキー(確認)</label><br>
        <%= f.password_field :password_confirmation, class:"title-content-room-index", placeholder:"（同じキーを入力してください)"%>
      </div>
      <div class="register-field-room-index">
        <%= f.submit class: "register-btn-room-index", value: "ルームを作成する" %>
      </div>
    </div>   
  <% end %>

  <div class="border"></div>
  <div class="room-list-title"><i class="fa-solid fa-paw"></i>Roomリスト<i class="fa-solid fa-paw"></i></div>
  <%# 検索欄 %>
  <div class="search-field">
    <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "(ルームを検索する)", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <%# ルーム一覧 %> 
  <div class="room-list">
    <div class="room-list-supplement">(作成日時順)</div>
      <% @rooms.each do |room| %>
        <div class="room">
          <div class="room-name">
            <%= link_to room.name, login_path%>
          </div>
          <div class="room-nickname">
            <% if current_user.id == room.user.id %>
              <%= link_to "編集(#{current_user.nickname})", edit_room_path(room.id)%>
            <% else %>
              <%= "作成：#{room.user.nickname}" %>
            <% end %>
          </div>
          <div class="room-date">
            <%= l room.created_at %>
          </div>
        </div>
      <% end %>
  </div>
</div> 
<%= render "shared/third-footer" %>

app/views/rooms/search.html.erb
<div class="wrapper">
  <%= render "shared/fourth-header" %>
  <div class="page-title-show"><i class="fa-solid fa-paw"></i>Roomページ<i class="fa-solid fa-paw"></i></div>

  <%= form_with model: @room, local: true do |f| %>
    <div class="new-room-wrapper">
      <%# エラーメッセージ%>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="article-post-room-index">
        <label for="name"><i class="fa-solid fa-house-circle-exclamation"></i>ルーム名(必須)</label><br>
        <%= f.text_field :name, class:"title-content-room-index", placeholder:"（40文字まで)", maxlength:"40"%>
      </div>
      <div class="article-post-room-index">
        <label for="password"><i class="fa-solid fa-key"></i>ルームキー(必須)</label><br>
        <%= f.password_field :password, class:"title-content-room-index", placeholder:"（ルームキーを設定してください)"%>
      </div>
      <div class="article-post-room-index">
        <label for="password_confirmation">ルームキー(確認)</label><br>
        <%= f.password_field :password_confirmation, class:"title-content-room-index", placeholder:"（同じキーを入力してください)"%>
      </div>
      <div class="register-field-room-index">
        <%= f.submit class: "register-btn-room-index", value: "ルームを作成する" %>
      </div>
    </div>   
  <% end %>

  <div class="border"></div>
  <div class="room-list-title"><i class="fa-solid fa-paw"></i>Roomリスト<i class="fa-solid fa-paw"></i></div>
  <%# 検索欄 %>
  <div class="search-field">
    <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "(ルームを検索する)", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <%# ルーム一覧 %> 
  <div class="room-list">
    <div class="room-list-supplement">(作成日順)</div>
      <% @rooms.each do |room| %>
        <div class="room">
          <div class="room-name">
            <%= link_to room.name, login_path%>
          </div>
          <div class="room-nickname">
            <% if current_user.id == room.user.id %>
              <%= link_to "ルームを編集する", edit_room_path(room.id) %>
            <% else %>
              <%= "作成者：#{room.user.nickname}さん" %>
            <% end %>
          </div>
          <div class="room-date">
            <%= l room.created_at %>
          </div>
        </div>
      <% end %>
    <% if @rooms.count == 0 %>
      <p class="search-nil">-ルームは見つかりませんでした-</p>
    <% end %>
  </div>
</div> 
<%= render "shared/third-footer" %>